### ISSUE TITLE
text-hates-you: Link to font-kit source repo instead

### ISSUE THREAD

**Issue by dgw** [Gankra/gankra.github.io#11]
The pcwalton fork appears to have disabled the wiki, so this link doesn't work any more:

https://github.com/Gankra/gankra.github.io/blob/0c74f3b0fbd70dc887c485c013fb132a6db33c74/blah/text-hates-you/index.md#L435

It looks like the intended target exists at https://github.com/servo/font-kit/wiki/FAQ

_**Note:** I have not made this into a PR because I'm not sure of the relationship between `index.md` and `index.html` in this site, so decided to leave regenerating the published version to you, the author. 😸_

**Comment by Gankra** [comment]
Oh, nice thank you! I was looking for where this went!
