### ISSUE TITLE
Please remove لا before بسم الله

### ISSUE THREAD

**Issue by mrhammadasif** [Gankra/gankra.github.io#7]
https://gankra.github.io/blah/text-hates-you/

Hi, Great article you have, but the Arabic words you chose, hurt the sentiments of many Muslims.

The phrase ` لا بسم الله` means "**NO**, We don't start with the name of Allah"

But there is no denying for us to start with the name of Allah. I hope you can understand and choose (or even change the order of wordings)

**Comment by Gankra** [comment]
Hey sorry for this, I got really mixed reports of the meaning of the phrase (did try to make it ~gibberish). The example has been changed to 

إلا بسم الله

This was provided to me by a native speaker who had similar concerns, let me know if it addresses yours too.

**Comment by mrhammadasif** [comment]
Thanks, Gankra. You are the best
